# Generated by Django 6.0.4 on 2026-04-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_store', '0002_alter_brand_slug_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, upload_to='icons/', verbose_name='Иконки'),
        ),
    ]
