# Generated by Django 6.0.4 on 2026-04-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_store', '0003_alter_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.FileField(blank=True, upload_to='icons/', verbose_name='Иконки'),
        ),
    ]
