# Generated by Django 6.0.4 on 2026-04-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_store', '0005_product_description_product_is_active_product_seller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Описание товара'),
        ),
    ]
