# Generated by Django 6.0.4 on 2026-04-23 11:47

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital_store', '0007_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='characteristic',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
