# Generated by Django 6.0.4 on 2026-05-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_store', '0010_alter_productimage_options_profileuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='address',
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile/', verbose_name='Фото профиля'),
        ),
    ]
