# Generated by Django 6.0.4 on 2026-05-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_store', '0011_remove_profileuser_address_alter_profileuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='image',
            field=models.ImageField(blank=True, default='https://i.pinimg.com/originals/5f/91/41/5f91413c8a9e766a5139c6cfe5caa837.jpg', upload_to='profile/', verbose_name='Фото профиля'),
        ),
    ]
