# Generated by Django 6.0.4 on 2026-05-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_store', '0012_alter_profileuser_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='buyer',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile/', verbose_name='Фото профиля'),
        ),
    ]
