# Generated by Django 6.0.4 on 2026-05-06 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_store', '0014_cart_productcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcart',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='digital_store.cart', verbose_name='Корзина'),
        ),
    ]
