# Generated by Django 6.0.4 on 2026-05-08 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital_store', '0016_alter_productcart_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
