# Generated by Django 6.0.4 on 2026-05-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_store', '0018_order_productorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.IntegerField(verbose_name='Цена заказа'),
        ),
    ]
