# Generated by Django 6.0.4 on 2026-05-08 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital_store', '0019_alter_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='order',
        ),
        migrations.RemoveField(
            model_name='productorder',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='ProductOrder',
        ),
    ]
