# Generated by Django 6.0.4 on 2026-05-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_store', '0021_delivery_order_productorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery',
        ),
        migrations.AlterModelOptions(
            name='productorder',
            options={'verbose_name': 'Товар заказа', 'verbose_name_plural': 'Товары заказ'},
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Комментария'),
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
