# Generated by Django 6.0.4 on 2026-05-12 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_store', '0022_remove_order_delivery_alter_productorder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_order', to='digital_store.product', verbose_name='Товар'),
        ),
    ]
