# Generated by Django 6.0.4 on 2026-05-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_store', '0025_alter_productorder_order_alter_productorder_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Доступно на складе'),
        ),
    ]
