# Generated by Django 6.0.4 on 2026-06-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_store', '0028_alter_cart_buyer_alter_order_buyer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='description',
            field=models.TextField(blank=True, max_length=800, verbose_name='Описание магазина'),
        ),
    ]
